# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/96013bca-b5f2-41b5-9aef-b7332ef60c16";
      fsType = "btrfs";
      options = [ "noatime,discard,subvol=root" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/96013bca-b5f2-41b5-9aef-b7332ef60c16";
      fsType = "btrfs";
      options = [ "noatime,discard,subvol=home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0179-3A6F";
      fsType = "vfat";
      options = [ "noatime" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/7a723fc5-90f6-406d-9858-18f61291c9da"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
